name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set timestamp
        shell: pwsh
        run: |
          $timestamp = Get-Date -UFormat %s
          echo "TIMESTAMP=$timestamp" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:${{ env.TIMESTAMP }}

