name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: self-hosted
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set timestamp
        run: |
          $timestamp = Get-Date -UFormat %s
          echo "TIMESTAMP=$timestamp" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name:  show GITHUB_WORKSPACE
        run: Write-Host "Workspace  $env:GITHUB_WORKSPACE"
        
      - name: Build Docker image
        run: |
          docker build -f Dockerfile -t isc-time-report-fe:$env:TIMESTAMP .

      - name: Run Docker container
        run: |
          docker run -d --rm -p 80:80 isc-time-report-fe:$env:TIMESTAMP

